### ISSUE TITLE
Using deterministic PT

### ISSUE THREAD

**Issue by helgehr** [SchweizerischeBundesbahnen/matsim-sbb-extensions#112]
Dear matsim/sbb community,

I have a problem using the deterministic public transport mode as pointed out in the `RunSBBExtension.java` file.
I use the Rail Raptor Module (which works fine) and want to add the `SBBTransitModule` as well, when I start a simulation I get the following error (also see attached logfile):
```log
2020-10-08T13:48:44,204  WARN AbstractQNetsimEngine:242 existing vehicle in mobsim was just overwritten by other vehicle with same ID.  Not clear what this means.  Continuing anyways ...
2020-10-08T13:48:44,205  WARN AbstractQNetsimEngine:243  This message given only once.
2020-10-08T13:48:44,205  WARN AbstractQLink:156 existing vehicle on link was just overwritten by other vehicle with same ID.  Not clear what this means.  Continuing anyways ...
2020-10-08T13:48:44,205  WARN AbstractQLink:157  This message given only once.
2020-10-08T13:48:44,206 ERROR QSim:357 got exception while cleaning up
java.lang.NullPointerException: null
```
[logfile.log](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/files/5347597/logfile.log)

I hope you can help and best regards!

**Comment by sarah-e-hayes** [comment]
Hi @helgehr - I don't have any suggestions unfortunately, but I'm in the same boat. My colleagues and I are trying to implement multiple SBB Extensions in the same controller. Similar to you we have the `Raptor` module working, but adding in the additional `SBBTransitModule` (adding lines to enable in controller as per [example](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/develop/src/main/java/ch/sbb/matsim/RunSBBExtension.java)  and into config as per [READme](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions#usage) ) causes a string of errors. 
Interestingly, different errors to the one you've posted - not sure if this sheds any more light on the problem?

```Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalAccessError: class ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine tried to access method 'void org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.<init>(org.matsim.core.mobsim.qsim.QSim)' (ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine and org.matsim.core.mobsim.qsim.pt.TransitQSimEngine are in unnamed module of loader 'app')
  at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine.<init>(SBBTransitQSimEngine.java:89)
  at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule.configureQSim(SBBTransitEngineQSimModule.java:15) (via modules: org.matsim.core.mobsim.qsim.QSimProvider$1 -> org.matsim.core.mobsim.qsim.AbstractQSimModule$1 -> com.google.inject.util.Modules$OverrideModule -> ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule)
  while locating ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine
  while locating org.matsim.core.mobsim.qsim.components.QSimComponent annotated with @com.google.inject.internal.Element(setName=@com.google.inject.name.Named(value="SBBTransit"),uniqueId=216, type=MULTIBINDER, keyType=)
  while locating org.matsim.core.mobsim.qsim.QSimProvider
  while locating org.matsim.core.mobsim.framework.Mobsim
Caused by: java.lang.IllegalAccessError: class ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine tried to access method 'void org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.<init>(org.matsim.core.mobsim.qsim.QSim)' (ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine and org.matsim.core.mobsim.qsim.pt.TransitQSimEngine are in unnamed module of loader 'app')
	at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine.<init>(SBBTransitQSimEngine.java:89)```
