### ISSUE TITLE
including "passengerModes" in transitModes

### ISSUE THREAD

**Issue by fredshone** [SchweizerischeBundesbahnen/matsim-sbb-extensions#124]
I am using Matsim v12 with raptor and mode mapping (not deterministic). As per the readme I have tried adding the mapped 'passengerModes' as transitModes:

```
 <module name="swissRailRaptor">
    <param name="useModeMappingForPassengers" value="true" />
    <parameterset type="modeMapping">
      <param name="routeMode" value="bus_dublin" />
      <param name="passengerMode" value="road" />
    </parameterset>
    <parameterset type="modeMapping">
      <param name="routeMode" value="subway" />
      <param name="passengerMode" value="rail" />
    </parameterset>
 </module>

 <module name="transit">
   <param name="transitModes" value="rail,road" />
 </module>
```

However this results in an error:

```
...
2020-12-23T20:47:34,886  INFO Counter:69 [PersonPrepareForSim] handled person # 1024
2020-12-23T20:47:34,886 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.7 died with exception while handling events.
org.matsim.core.router.TripRouter$UnknownModeException: unregistered main mode |bus_dublin|: does not pertain to [pt, road, rail, walk]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:189) ~[columbus-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94) ~[columbus-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:221) ~[columbus-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145) ~[columbus-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-12-23T20:47:34,932 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.6 died with exception while handling events.
...
```

This is fixed by adding the scheduled modes (in this case bus_dublin and subway) to the transitModes, eg:

```
 <module name="transit">
   <param name="transitModes" value="rail,road,bus_dublin,subway" />
 </module>
```

Is this expected?

-----------------------

For additional context, I only recently came accoss this because I was previously using passengerModes equal to the transitModes, eg:

```
 <module name="swissRailRaptor">
    <param name="useModeMappingForPassengers" value="true" />
    <parameterset type="modeMapping">
      <param name="routeMode" value="bus_dublin" />
      <param name="passengerMode" value="bus_dublin" />
    </parameterset>
    <parameterset type="modeMapping">
      <param name="routeMode" value="subway" />
      <param name="passengerMode" value="subway" />
    </parameterset>
 </module>
```

which runs fine.

**Comment by fredshone** [comment]
if expected I propose clarifying in the readme [here](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions#differentiating-pt-sub-modes), ie:

**Comment by mrieser** [comment]
Thanks for reporting this! I have rarely used the mode mapping and will probably have to re-create a small scenario to test this. I think you are right, but I'll leave the issue open as a reminder for me to look into this and into improving the readme.
