### ISSUE TITLE
Unable to use deterministic PT

### ISSUE THREAD

**Issue by fredshone** [SchweizerischeBundesbahnen/matsim-sbb-extensions#125]
I am using Matsim v12 with raptor and mode mapping. When I try to add the deterministic module I get the following error (in full further below):

```
Error injecting constructor, java.lang.IllegalAccessError: class ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine tried to access method 'void org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.<init>(org.matsim.core.mobsim.qsim.QSim)' (ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine and org.matsim.core.mobsim.qsim.pt.TransitQSimEngine are in unnamed module of loader 'app')
```

This occurs with or without modeMapping enabled. Any guidance with the trace greatly appreciated. RunMatsim as follows:
```
public class RunMatsimTIIDev {
    public static void main(String[] args) {
        String configFilename = args[0];
        Config config = ConfigUtils.loadConfig(configFilename);
        Scenario scenario = ScenarioUtils.loadScenario(config);
        Controler controler = new Controler(scenario);
        controler.addOverridingModule(new SBBTransitModule());
        controler.addOverridingModule(new SwissRailRaptorModule());
        controler.configureQSimComponents(components -> {
                SBBTransitEngineQSimModule.configure(components);
        });
        controler.run();
    }
}
```

----------------

```
...
2020-12-23T21:42:50,092  INFO Counter:69 [PersonPrepareForSim] handled person # 32768
2020-12-23T21:42:50,108  INFO Counter:74 [PersonPrepareForSim] handled person # 42489
2020-12-23T21:42:50,179  INFO MobsimListenerManager:49 calling addQueueSimulationListener
2020-12-23T21:42:50,180  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimInitializedListener
2020-12-23T21:42:50,180  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimAfterSimStepListener
2020-12-23T21:42:50,180  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeCleanupListener
2020-12-23T21:42:50,180  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.vis.snapshotwriters.SnapshotWriterManager
2020-12-23T21:42:50,180  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-12-23T21:42:51,780 ERROR AbstractController:209 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalAccessError: class ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine tried to access method 'void org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.<init>(org.matsim.core.mobsim.qsim.QSim)' (ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine and org.matsim.core.mobsim.qsim.pt.TransitQSimEngine are in unnamed module of loader 'app')
  at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine.<init>(SBBTransitQSimEngine.java:89)
  at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule.configureQSim(SBBTransitEngineQSimModule.java:15) (via modules: org.matsim.core.mobsim.qsim.QSimProvider$1 -> org.matsim.core.mobsim.qsim.AbstractQSimModule$1 -> com.google.inject.util.Modules$OverrideModule -> ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule)
  while locating ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine
  while locating org.matsim.core.mobsim.qsim.components.QSimComponent annotated with @com.google.inject.internal.Element(setName=@com.google.inject.name.Named(value="SBBTransit"),uniqueId=374, type=MULTIBINDER, keyType=)
  while locating org.matsim.core.mobsim.qsim.QSimProvider
  while locating org.matsim.core.mobsim.framework.Mobsim
Caused by: java.lang.IllegalAccessError: class ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine tried to access method 'void org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.<init>(org.matsim.core.mobsim.qsim.QSim)' (ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine and org.matsim.core.mobsim.qsim.pt.TransitQSimEngine are in unnamed module of loader 'app')
	at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine.<init>(SBBTransitQSimEngine.java:89)
	at ch.sbb.matsim.mobsim.qsim.pt.SBBTransitQSimEngine$$FastClassByGuice$$a6e054ee.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at org.matsim.core.mobsim.qsim.QSimProvider.get(QSimProvider.java:84)
	at org.matsim.core.mobsim.qsim.QSimProvider.get(QSimProvider.java:46)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at com.arup.cm.RunMatsimTIIDev.main(RunMatsimTIIDev.java:41)
```

**Comment by KasiaKoz** [comment]
This error exists without any mention of differentiated PT via mode mappings or deterministic PT in the config. Using the following to run matsim (which works for us with matsim v11 and coincides with the example [RunSBBExtension](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/master/src/main/java/ch/sbb/matsim/RunSBBExtension.java))

```java
package com.arup.cm;

import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.controler.Controler;

import ch.sbb.matsim.mobsim.qsim.SBBTransitModule;
import ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule;
import ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule;

public class RunMatsim {
    public static void main(String[] args) {

        //load config 
        Config config = ConfigUtils.loadConfig(args[0]);
        Controler controler = new Controler(config);

        controler.addOverridingModule(new SBBTransitModule());
        controler.addOverridingModule(new SwissRailRaptorModule());
        controler.configureQSimComponents(components -> {SBBTransitEngineQSimModule.configure(components);});
        controler.run();
    }
}
```

with this pretty basic config:
```xml
<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>

	<module name="global">
		<param name="randomSeed" value="4711" />
		<param name="coordinateSystem" value="EPSG:27700" />
	        <param name="numberOfThreads" value="1" />
	</module>

	<module name="network">
		<param name="inputNetworkFile" value="./network.xml" />
	</module>

	<module name="plans">
		<param name="insistingOnUsingDeprecatedPersonAttributeFile" value="true" />
		<param name="inputPlansFile" value="./population.xml" />
		<param name="inputPersonAttributesFile" value="./attributes.xml" />
		<!--<param name="subpopulationAttributeName" value="subpopulation" />-->
	</module>

	<module name="transit">
		<param name="useTransit" value="true" />
		<param name="transitScheduleFile" value="./transitschedule.xml" />
		<param name="vehiclesFile" value="./transitVehicles.xml" />
		<param name="transitModes" value="pt" />
	</module>

	<module name="TimeAllocationMutator">
	        <param name="mutationRange" value="1000.0"/>
	</module>

	<module name="controler">
    <param name="createGraphs" value="false" />
		<param name="outputDirectory" value="mnt/test_outputs-vanilla/RunMatsim_outputs" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="1" />
		<param name="eventsFileFormat" value="xml" />
		<param name="writeEventsInterval" value="1" />
		<param name="writePlansInterval" value="1" />
		<param name="mobsim" value="qsim" />
   	<param name="snapshotFormat" value="" />

		<!-- Possible values: failIfDirectoryExists, overwriteExistingFiles, deleteDirectoryIfExists -->
		<param name="overwriteFiles" value="overwriteExistingFiles" />
	</module>

	<module name="subtourModeChoice">
        <param name="chainBasedModes" value="car,cycle" />
        <param name="modes" value="car,pt,walk,cycle" />
       </module>

	<module name="parallelEventHandling">
		<param name = "estimatedNumberOfEvents" value="null"/>
		<param name = "numberOfThreads" value="1"/>
	</module>

	<module name="qsim">

		<!-- "start/endTime" of MobSim (00:00:00 == take earliest activity time/ run as long as active vehicles exist) -->

		<param name="startTime" value="00:00:00" />
		<param name="endTime" value="24:00:00" />

		<!-- The list of modes found in the inputted vehicle schedule file -->
		<param name="mainMode" value="car,bus,cycle" />

		<param name="numberOfThreads" value="1" />

		<param name = "flowCapacityFactor" value = "1"/> <!-- Don't forget to change this to match sample-->
		<param name = "storageCapacityFactor" value = "1"/> <!-- Don't forget to change this to -->

		<param name = "usingFastCapacityUpdate" value="true"/>
	</module>

	<module name="planscalcroute" >
		<param name="networkModes" value="car,cycle" />
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="access_walk" />

			<!-- Free-speed factor for a teleported mode. Travel time = teleportedModeFreespeedFactor * <freespeed car travel time>. Insert a line like this for every such mode. Please do not set teleportedModeFreespeedFactor as well as teleportedModeSpeed for the same mode, but if you do, +teleportedModeFreespeedFactor wins over teleportedModeSpeed. -->
			<param name="teleportedModeFreespeedFactor" value="null" />

			<!-- Speed for a teleported mode. Travel time = (<beeline distance> * beelineDistanceFactor) / teleportedModeSpeed. Insert a line like this for every such mode. -->
			<param name="teleportedModeSpeed" value="0.8333333333333333" />
		</parameterset>
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="walk" />

			<!-- Free-speed factor for a teleported mode. Travel time = teleportedModeFreespeedFactor * <freespeed car travel time>. Insert a line like this for every such mode. Please do not set teleportedModeFreespeedFactor as well as teleportedModeSpeed for the same mode, but if you do, +teleportedModeFreespeedFactor wins over teleportedModeSpeed. -->
			<param name="teleportedModeFreespeedFactor" value="null" />

			<!-- Speed for a teleported mode. Travel time = (<beeline distance> * beelineDistanceFactor) / teleportedModeSpeed. Insert a line like this for every such mode. -->
			<param name="teleportedModeSpeed" value="0.8333333333333333" />
		</parameterset>
	</module>

	<module name="planCalcScore">

		<param name="BrainExpBeta" value="1.0" />

... scoring params for all subpopulations

	</module>

	<module name="strategy">

		<param name="maxAgentPlanMemorySize" value="3" />

... stategy settings for all subpopulations

	 </module>
</config>
```

The error seems to appear just by having 
```java
import ch.sbb.matsim.mobsim.qsim.SBBTransitModule;
import ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule;
...
        controler.addOverridingModule(new SBBTransitModule());
        controler.configureQSimComponents(components -> {SBBTransitEngineQSimModule.configure(components);});

```
present. Without this, raptor runs fine, and adding mode mappings for differentiated PT modes also works as expected.

Java is not my language but I think I notice that in v12 `ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule` comes from [matsim code base](https://github.com/matsim-org/matsim-libs/tree/12.x/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor) whereas `ch.sbb.matsim.mobsim.qsim....` comes from [ssb extensions](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/tree/master/src/main/java/ch/sbb/matsim/mobsim/qsim), which was not the case with v11, they both came from extensions. To that end, we ensure that in the dependencies in our `pom.xml` file we match matsim and ssb extension versions for v11 and v12 alike, e.g.
```xml
    <dependencies>
        <dependency>
            <!-- This is the matsim "core": -->
            <groupId>org.matsim</groupId>
            <artifactId>matsim</artifactId>
            <version>12.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.SchweizerischeBundesbahnen</groupId>
            <artifactId>matsim-sbb-extensions</artifactId>
            <version>12.0</version>
        </dependency>
    </dependencies>
```

**Comment by jfbischoff** [comment]
Hi,

yes, you should keep the sbb-extensions at roughly the same version as MATSim. That is one reason that as of now they have become a MATSim Contrib (i.e., if you use the latest 13.0-2021w01-SNAPSHOT - weekly for MATSim you can simply add the same version for the contrib). See the current readme of sbb-extensions for the latest installation
-----
If you want to continue to use MATSim 12.0 release then I would recommend using version 12.3, this was released using the MATSim 12.0 release as a dependency and should be fully compatible. Please follow the installation instructions described here:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/tree/6536750165854ce01cf8ad03062570ed77059dbf

**Comment by gac55** [comment]
Hi all, 

Just wanted to round this out. Thanks to @jfbischoff for the help.

This was fixed by importing the `SBBTransitConfigGroup` and instantiating it,

so additions to our controller:

```
// standard imports plus: 
import ch.sbb.matsim.config.SBBTransitConfigGroup;

   // standard stuff plus: 
    ConfigUtils.addOrGetModule(config, SBBTransitConfigGroup.class);
    controler.addOverridingModule(new SBBTransitModule());
```

**Comment by gac55** [comment]
For completeness, the controller therefore looked like:

```
package com.arup.cm;

import org.apache.log4j.Logger;

import org.matsim.api.core.v01.Scenario;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.controler.Controler;
import org.matsim.core.scenario.ScenarioUtils;

import ch.sbb.matsim.mobsim.qsim.SBBTransitModule;
import ch.sbb.matsim.config.SBBTransitConfigGroup;
import ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule;
import ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule;
import org.matsim.contrib.roadpricing.RoadPricingModule;
import org.matsim.contrib.roadpricing.RoadPricingUtils;
import org.matsim.contrib.roadpricing.RoadPricingConfigGroup;

public class RunMatsimTIIRP {

    public static void main(String[] args) {

        String configFilename = args[0];
        Config config = ConfigUtils.loadConfig(configFilename, RoadPricingUtils.createConfigGroup());
	    ConfigUtils.addOrGetModule(config, RoadPricingConfigGroup.class).setTollLinksFile(args[1]);
        
        ConfigUtils.addOrGetModule(config, SBBTransitConfigGroup.class);
        
        Scenario scenario = ScenarioUtils.loadScenario(config);
        Controler controler = new Controler(scenario);

        controler.addOverridingModule(new RoadPricingModule());
        controler.addOverridingModule(new SBBTransitModule());
        controler.addOverridingModule(new SwissRailRaptorModule());
        
        controler.run();
    }
}
```
