### ISSUE TITLE
RuntimeException: Unmaterialized config group: SBBPt

### ISSUE THREAD

**Issue by davibicudo** [SchweizerischeBundesbahnen/matsim-sbb-extensions#3]
Hi!

Trying to run the extensions for the first time returned this error. The logs are attached in case it's worth looking at and the stack trace was:

2018-03-21 15:07:43,980 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: SBBPt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:228)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:89)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at simulation.RunMATSim.run(RunMATSim.java:42)
	at simulation.RunMATSim.main(RunMATSim.java:18)
2018-03-21 15:07:43,981  INFO MatsimRuntimeModifications:58 S H U T D O W N   ---   start shutdown.
2018-03-21 15:07:43,981 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2018-03-21 15:07:43,982 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Unmaterialized config group: SBBPt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:228)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:89)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at simulation.RunMATSim.run(RunMATSim.java:42)
	at simulation.RunMATSim.main(RunMATSim.java:18)
2018-03-21 15:07:43,983  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2018-03-21 15:07:43,983  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2018-03-21 15:07:43,983  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2018-03-21 15:07:43,985  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2018-03-21 15:07:43,986  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener
2018-03-21 15:07:43,987  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2018-03-21 15:07:43,987 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2018-03-21 15:07:43,988 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2018-03-21 15:07:43,989  INFO MatsimRuntimeModifications:81 S H U T D O W N   ---   shutdown completed.
2018-03-21 15:07:43,989 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Unmaterialized config group: SBBPt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:228)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:89)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at simulation.RunMATSim.run(RunMATSim.java:42)
	at simulation.RunMATSim.main(RunMATSim.java:18)

[logfile.log](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/files/1833630/logfile.log)
[logfileWarningsErrors.log](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/files/1833631/logfileWarningsErrors.log)

**Comment by mrieser** [comment]
Hi,

How are you using the extension? Do you just use RunSBBExtension as main class, or have you somehow integrated it into your own controller?

I'll have a closer look at the issue, my current guess is that a line is missing in RunSBBExtension.

In the meantime, if you don't use RunSBBExtension, make sure to explicitly add the SBBPt-config class to your config object. This can be done when you create the initial config-object in your main class, e.g.:

`Config config = ConfigUtils.loadConfig(configFilename, new SBBTransitConfigGroup());
`
I'll check that RunSBBExtension, or the SBBQSimModule, register the config group correctly in the future.

**Comment by davibicudo** [comment]
Hi Marcel, thanks for the quick reply.

I was simply calling the RunSBBExtension's main.
With the change you suggested it is now working, although there was a problem with the param name. createLinkEventsInterval was rejected and the correct one was createLinkEvents so you might want to change the README too.

**Comment by mrieser** [comment]
If you had to change `createLinkEventsInterval` to `createLinkEvents`, than you likely used version 0.9.1 as a dependency. In version 0.9.2, it was changed to the inverval in order to better control the functionality and reduce possible overhead during the simulation.

**Comment by mrieser** [comment]
Okay, we've fixed the original issue (RuntimeException: Unmaterialized config group: SBBPt) internally and the fix will be included in the next release. Thus closing the issue for now.
