### ISSUE TITLE
could not find requested vehicle (...) SBBTransitDriverAgent

### ISSUE THREAD

**Issue by davibicudo** [SchweizerischeBundesbahnen/matsim-sbb-extensions#4]
Hi Marcel,

Do you know what might be the cause of this error? It is a bit obscure to me.
Thanks a lot!

Davi

Exception in thread "main" java.lang.RuntimeException: could not find requested vehicle veh_30080_rail in simulation for agent ch.sbb.matsim.mobsim.qsim.pt.SBBTransitDriverAgent@65048b0b with id pt_4_23-4-A-j17-1_151.TA.23-4-A-j17-1.49.H_151.TA.23-4-A-j17-1.49.H_00:03:00 on link pt_8501120:0:5 at time 180.0. aborting ...
	at org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler.handleCarDeparture(VehicularDepartureHandler.java:83)
	at org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler.handleDeparture(VehicularDepartureHandler.java:56)
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:441)
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:406)
	at org.matsim.core.mobsim.qsim.QSim.access$000(QSim.java:98)
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:151)
	at org.matsim.core.mobsim.qsim.ActivityEngine.doSimStep(ActivityEngine.java:117)
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:361)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:237)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:29)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at simulation.RunMATSim.run(RunMATSim.java:70)
	at simulation.RunMATSim.main(RunMATSim.java:23)

**Comment by mrieser** [comment]
Most likely, you configured the same modes as deterministic modes in the `SBBPt` config group as well as `mainMode` in the `qsim` config group. In such a case, deterministic drivers are generated without vehicles (as they are not required by the deterministic simulation). But later, as they are configured in the main mode, the simulation tries to start them on the network, and then the vehicles are missing.
I'll add a check that outputs a warning or even an exception if such a misconfiguration is found in order to provide a more meaningful error message in the future.

**Comment by davibicudo** [comment]
That was it. Thanks!
